markdown: kramdown
remote_theme: just-the-docs/just-the-docs
aux_links:
  "Model Recycling on GitHub":
    - "//github.com/IBM/model-recycling"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
# Footer - "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"

